# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93117a32dde88ef26fdd13e6cd97de0e1a767d805d69c8e3874928a1b06b514f04ed2b683f286636fb16b0f900b4ec99415045fdcc2084c24e7f27f019b2b3df

test:
  secret_key_base: 6975c4981810bcbedabfa308c1e1793502962e3c1e0084c962ac1aa13310073a7c00b7f922758ef1cb13a9634c533ad8af8119dfc2536535e569851f83467e91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
